# Generated by Django 3.2.3 on 2021-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
