# Generated by Django 3.2.3 on 2021-07-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0004_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.FileField(upload_to='images'),
        ),
    ]
