# Generated by Django 3.2.5 on 2021-07-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0008_alter_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
    ]
